SetTags: true #устанавливать ли теги игрокам при входе (плагин может работать как API)
DefaultGroup: default #дефолтная группа
Positions: #позиции групп (по алфавиту)
  owner: A
  admin: B
  moder: C
  helper: D
  builder: D
  ultra: E
  elite: F
  premium: O
  vip: J
  default: Z