name: ProtocolTags
main: ru.dondays.protocoltags.ProtocolTags
version: 1.2a
author: DonDays
description: Universal, simple tag manager implementing useful API
depend: [PermissionsEx, ProtocolLib]
commands:
  protocoltags: